In [5]:
import pandas as pd

# This uses the path you just selected
df = pd.read_csv("netflix_titles .csv")

# Verify success
print("Success! Data loaded.")
print(df.shape)
df.head()

Success! Data loaded.
(8807, 12)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
# Count the total number of duplicate rows
duplicate_count = df.duplicated().sum()
print(f"Total duplicate rows: {duplicate_count}")

# (Optional) See which rows are duplicates
if duplicate_count > 0:
    print(df[df.duplicated()])

Total duplicate rows: 0

In [7]:
# Count missing values for each column
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values)

Missing values per column:
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [8]:
# 1. Handle specific null values as requested
cols_to_fix = ['director', 'cast', 'country']
df[cols_to_fix] = df[cols_to_fix].fillna('notavailable')

# 2. Check for any remaining null values in other columns
print("Missing values after update:")
print(df.isnull().sum())

# 3. Check for duplicates (as you mentioned earlier)
print(f"\nNumber of duplicate rows: {df.duplicated().sum()}")

# 4. If there are duplicates, remove them
df.drop_duplicates(inplace=True)

# Preview the cleaned data
df.head()

Missing values after update:
show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64

Number of duplicate rows: 0

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,notavailable,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,notavailable,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",notavailable,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,notavailable,notavailable,notavailable,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,notavailable,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [9]:
# 1. Replace nulls in specific columns with 'notavailable'
cols_to_fix = ['director', 'cast', 'country']
df[cols_to_fix] = df[cols_to_fix].fillna('notavailable')

# 2. Drop rows where 'rating', 'duration', or 'date_added' are null
df.dropna(subset=['rating', 'duration', 'date_added'], inplace=True)

# 3. Final Check: Verify no nulls remain in the entire dataset
print("Final Null Value Count:")
print(df.isnull().sum())

# 4. Check for and remove any duplicate rows
duplicate_count = df.duplicated().sum()
if duplicate_count > 0:
    print(f"\nRemoving {duplicate_count} duplicate rows...")
    df.drop_duplicates(inplace=True)

# Show the cleaned data info
print("\nCleaned Dataset Info:")
print(df.info())

Final Null Value Count:
show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

Cleaned Dataset Info:
<class 'pandas.core.frame.DataFrame'>
Index: 8790 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   cast          8790 non-null   object
 5   country       8790 non-null   object
 6   date_added    8790 non-null   object
 7   release_year  8790 non-null   int64
 8   rating        8790 non-null   object
 9   duration      8790 non-null   object
 10  listed_in     8790 non-null   object
 11  description   8790 non-null   object
dtypes: int64(1), object(11)
memory usage: 892.7+ KB
None

In [10]:
# 1. First, convert the column to a proper Datetime object
# We use errors='coerce' just in case there are any weird characters left
df['date_added'] = pd.to_datetime(df['date_added'].str.strip())

# 2. Extract the Year and convert it to int64
# We fill any remaining NaTs (Not a Time) with 0 before converting to integer
df['date_added_year'] = df['date_added'].dt.year.fillna(0).astype('int64')

# 3. If you want the original column name to be the int64 year:
# df['date_added'] = df['date_added'].dt.year.fillna(0).astype('int64')

# Verify the data types
print(df[['date_added', 'date_added_year']].dtypes)
df[['title', 'date_added', 'date_added_year']].head()

date_added         datetime64[ns]
date_added_year             int64
dtype: object

                   title date_added  date_added_year
0   Dick Johnson Is Dead 2021-09-25             2021
1          Blood & Water 2021-09-24             2021
2              Ganglands 2021-09-24             2021
3  Jailbirds New Orleans 2021-09-24             2021
4           Kota Factory 2021-09-24             2021

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8790 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   show_id          8790 non-null   object
 1   type             8790 non-null   object
 2   title            8790 non-null   object
 3   director         8790 non-null   object
 4   cast             8790 non-null   object
 5   country          8790 non-null   object
 6   date_added       8790 non-null   datetime64[ns]
 7   release_year     8790 non-null   int64
 8   rating           8790 non-null   object
 9   duration         8790 non-null   object
 10  listed_in        8790 non-null   object
 11  description      8790 non-null   object
 12  date_added_year  8790 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(10)
memory usage: 961.4+ KB

In [1]:
import pandas as pd
df = pd.read_csv("netflix_titles .csv")
# 1. Convert the string to a Datetime object first
# We use errors='coerce' to turn any messy data into 'NaT' (Not a Time)
df['date_added'] = pd.to_datetime(df['date_added'].str.strip(), errors='coerce')

# 2. Extract the year and fill any missing values with 0 so we can convert to integer
# (Since you already dropped nulls in the previous step, this is just a safety measure)
df['date_added'] = df['date_added'].dt.year.fillna(0).astype('int64')

# 3. Verify the change
print(df[['title', 'date_added']].info())
df[['title', 'date_added']].head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       8807 non-null   object
 1   date_added  8807 non-null   int64
dtypes: int64(1), object(1)
memory usage: 137.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8807 non-null   int64
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(2), object(10)
memory usage: 825.8+ KB

In [2]:
# 1. Check for Null Values
print("--- Null Value Check ---")
print(df.isnull().sum())

# 2. Check for Duplicate Rows
# (Netflix data sometimes has duplicates if a title was re-added)
duplicates = df.duplicated().sum()
print(f"\n--- Duplicate Check ---")
print(f"Total duplicate rows found: {duplicates}")

# 3. Final Type Verification
print(f"\n--- Data Type Check ---")
print(df[['date_added']].dtypes)

# 4. If duplicates exist, run this to remove them:
if duplicates > 0:
    df.drop_duplicates(inplace=True)
    print("\nAction: Duplicates removed.")

--- Null Value Check ---
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added         0
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

--- Duplicate Check ---
Total duplicate rows found: 0

--- Data Type Check ---
date_added    int64
dtype: object

In [3]:
# 1. Permanent Replacement for categorical columns
# We assign the result back to the columns to ensure they 'stick'
df['director'] = df['director'].fillna('notavailable')
df['cast'] = df['cast'].fillna('notavailable')
df['country'] = df['country'].fillna('notavailable')

# 2. Permanent Drop for the small null counts (Rating and Duration)
# 'inplace=True' makes the change directly to the dataframe
df.dropna(subset=['rating', 'duration'], inplace=True)

# 3. FINAL VERIFICATION
print("--- Final Null Value Count ---")
print(df.isnull().sum())

--- Final Null Value Count ---
show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [4]:
# 1. Check for Null Values
print("--- Null Value Check ---")
print(df.isnull().sum())

# 2. Check for Duplicate Rows
# (Netflix data sometimes has duplicates if a title was re-added)
duplicates = df.duplicated().sum()
print(f"\n--- Duplicate Check ---")
print(f"Total duplicate rows found: {duplicates}")

# 3. Final Type Verification
print(f"\n--- Data Type Check ---")
print(df[['date_added']].dtypes)

# 4. If duplicates exist, run this to remove them:
if duplicates > 0:
    df.drop_duplicates(inplace=True)
    print("\nAction: Duplicates removed.")

--- Null Value Check ---
show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

--- Duplicate Check ---
Total duplicate rows found: 0

--- Data Type Check ---
date_added    int64
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8800 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8800 non-null   object
 1   type          8800 non-null   object
 2   title         8800 non-null   object
 3   director      8800 non-null   object
 4   cast          8800 non-null   object
 5   country       8800 non-null   object
 6   date_added    8800 non-null   int64
 7   release_year  8800 non-null   int64
 8   rating        8800 non-null   object
 9   duration      8800 non-null   object
 10  listed_in     8800 non-null   object
 11  description   8800 non-null   object
dtypes: int64(2), object(10)
memory usage: 893.8+ KB

In [6]:
# 1. Check for Null Values
print("--- Null Value Check ---")
print(df.isnull().sum())

# 2. Check for Duplicate Rows
# (Netflix data sometimes has duplicates if a title was re-added)
duplicates = df.duplicated().sum()
print(f"\n--- Duplicate Check ---")
print(f"Total duplicate rows found: {duplicates}")

# 3. Final Type Verification
print(f"\n--- Data Type Check ---")
print(df[['date_added']].dtypes)

# 4. If duplicates exist, run this to remove them:
if duplicates > 0:
    df.drop_duplicates(inplace=True)
    print("\nAction: Duplicates removed.")

--- Null Value Check ---
show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

--- Duplicate Check ---
Total duplicate rows found: 0

--- Data Type Check ---
date_added    int64
dtype: object