In [32]:
import pandas as pd

In [34]:
df = pd.read_csv("netflix_cleaned_week2.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## Task 4: Normalize categorical features such as genre, rating, and country.

In [37]:
df.select_dtypes(include='object').columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [39]:
df = df.fillna("unknown")

In [41]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

In [43]:
df['rating'].value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
unknown        4
NC-17          3
UR             3
66 min         1
74 min         1
84 min         1
Name: count, dtype: int64

In [45]:
df[df['rating'].str.contains('MIN')]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [47]:
df.loc[df['rating'].str.contains('MIN'), 'duration'] = df['rating']

In [49]:
import numpy as np

df.loc[df['rating'].str.contains('MIN'), 'rating'] = np.nan

In [51]:
df['rating'].value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
unknown        4
NC-17          3
UR             3
66 min         1
74 min         1
84 min         1
Name: count, dtype: int64

In [53]:
df['rating'].fillna(df['rating'].mode()[0], inplace=True)

C:\Users\daayu\AppData\Local\Temp\ipykernel_20304\2284108631.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['rating'].fillna(df['rating'].mode()[0], inplace=True)

In [55]:
df['rating'].isnull().sum()

np.int64(0)

In [57]:
df['release_year'] = df['release_year'].astype(str)

In [59]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['release_year'] = pd.to_datetime(df['release_year'], format='%Y')

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      8807 non-null   object
 4   cast          8807 non-null   object
 5   country       8807 non-null   object
 6   date_added    8797 non-null   datetime64[ns]
 7   release_year  8807 non-null   datetime64[ns]
 8   rating        8807 non-null   object
 9   duration      8807 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](2), object(10)
memory usage: 825.8+ KB

In [63]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,unknown,United States,2021-09-25,2020-01-01,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021-01-01,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,2021-09-24,2021-01-01,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,unknown,unknown,unknown,2021-09-24,2021-01-01,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021-01-01,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [65]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

In [67]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.lower()

In [69]:
df['rating'] = df['rating'].replace({
    'tv-ma': 'TV-MA',
    'tv ma': 'TV-MA',
    'tv-14': 'TV-14'
})

In [71]:
df['rating'].unique()

array(['pg-13', 'TV-MA', 'pg', 'TV-14', 'tv-pg', 'tv-y', 'tv-y7', 'r',
       'tv-g', 'g', 'nc-17', '74 min', '84 min', '66 min', 'nr',
       'unknown', 'tv-y7-fv', 'ur'], dtype=object)

In [73]:
df['duration_number'] = df['duration'].str.extract(r'(\d+)').astype(float)

In [75]:
df['duration_type'] = df['duration'].str.extract('([a-zA-Z]+)')

In [77]:
df['duration_type'] = df['duration_type'].replace({
    'seasons':'season'
})

In [79]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_number,duration_type
0,s1,movie,dick johnson is dead,kirsten johnson,unknown,united states,2021-09-25,2020-01-01,pg-13,90 min,documentaries,"as her father nears the end of his life, filmm...",90.0,min
1,s2,tv show,blood & water,unknown,"ama qamata, khosi ngema, gail mabalane, thaban...",south africa,2021-09-24,2021-01-01,TV-MA,2 seasons,"international tv shows, tv dramas, tv mysteries","after crossing paths at a party, a cape town t...",2.0,season
2,s3,tv show,ganglands,julien leclercq,"sami bouajila, tracy gotoas, samuel jouy, nabi...",unknown,2021-09-24,2021-01-01,TV-MA,1 season,"crime tv shows, international tv shows, tv act...",to protect his family from a powerful drug lor...,1.0,season
3,s4,tv show,jailbirds new orleans,unknown,unknown,unknown,2021-09-24,2021-01-01,TV-MA,1 season,"docuseries, reality tv","feuds, flirtations and toilet talk go down amo...",1.0,season
4,s5,tv show,kota factory,unknown,"mayur more, jitendra kumar, ranjan raj, alam k...",india,2021-09-24,2021-01-01,TV-MA,2 seasons,"international tv shows, romantic tv shows, tv ...",in a city of coaching centers known to train i...,2.0,season

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   show_id          8807 non-null   object
 1   type             8807 non-null   object
 2   title            8807 non-null   object
 3   director         8807 non-null   object
 4   cast             8807 non-null   object
 5   country          8807 non-null   object
 6   date_added       8797 non-null   datetime64[ns]
 7   release_year     8807 non-null   datetime64[ns]
 8   rating           8807 non-null   object
 9   duration         8807 non-null   object
 10  listed_in        8807 non-null   object
 11  description      8807 non-null   object
 12  duration_number  8804 non-null   float64
 13  duration_type    8807 non-null   object
dtypes: datetime64[ns](2), float64(1), object(11)
memory usage: 963.4+ KB

In [83]:
df['type'] = df['type'].str.title()
df['title'] = df['title'].str.title()
df['director'] = df['director'].str.title()
df['cast'] = df['cast'].str.title()
df['country'] = df['country'].str.title()
df['rating'] = df['rating'].str.upper()
df['listed_in'] = df['listed_in'].str.title()

In [84]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_number,duration_type
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020-01-01,PG-13,90 min,Documentaries,"as her father nears the end of his life, filmm...",90.0,min
1,s2,Tv Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021-01-01,TV-MA,2 seasons,"International Tv Shows, Tv Dramas, Tv Mysteries","after crossing paths at a party, a cape town t...",2.0,season
2,s3,Tv Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021-01-01,TV-MA,1 season,"Crime Tv Shows, International Tv Shows, Tv Act...",to protect his family from a powerful drug lor...,1.0,season
3,s4,Tv Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021-01-01,TV-MA,1 season,"Docuseries, Reality Tv","feuds, flirtations and toilet talk go down amo...",1.0,season
4,s5,Tv Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021-01-01,TV-MA,2 seasons,"International Tv Shows, Romantic Tv Shows, Tv ...",in a city of coaching centers known to train i...,2.0,season

In [85]:
df_clean = df.copy()
df_clean.to_csv("netflix_cleaned_week3.csv", index=False)